name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - test-branch

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform: [ios, macos, chrome, android]
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
          channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
      working-directory: ./flutter_application_main
    - name: Run analyze
      run: flutter analyze
      working-directory: ./flutter_application_main
    - name: Run tests
      run: flutter test
      working-directory: ./flutter_application_main

  test-ios-simulator:
    needs: test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 14'
      - run: flutter pub get
        working-directory: ./flutter_application_main
      - run: flutter test integration_test
        working-directory: ./flutter_application_main

  build:
    needs: [test, test-ios-simulator]
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform: [ios, macos, chrome, android]
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
          channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
      working-directory: ./flutter_application_main
    - name: Build app for ${{ matrix.platform }}
      run: |
        if [ "${{ matrix.platform }}" == "ios" ]; then
          flutter build ios --release
        elif [ "${{ matrix.platform }}" == "macos" ]; then
          flutter build macos --release
        elif [ "${{ matrix.platform }}" == "chrome" ]; then
          flutter build web --release
        else
          flutter build apk --release
        fi
      working-directory: ./flutter_application_main

  release:
    needs: build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false
