name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - test-branch

jobs:
  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
          channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
      working-directory: ./flutter_application_main
    - name: Run analyze
      run: flutter analyze
      working-directory: ./flutter_application_main
    - name: Run tests
      run: flutter test
      working-directory: ./flutter_application_main
    - name: Boot Simulator
      run: |
        DEVICE_ID=$(xcrun simctl list devices available --json | jq -r '.devices[] | .[] | select(.name == "iPhone 14") | .udid' | head -n 1)
        if [ -z "$DEVICE_ID" ]; then
          echo "Specified device not found, falling back to default simulator"
          DEVICE_ID=$(xcrun simctl list devices available --json | jq -r '.devices[] | .[] | .udid' | head -n 1)
        fi
        echo "Using device ID $DEVICE_ID"
        xcrun simctl boot "$DEVICE_ID"
    - name: Install dependencies
      run: flutter pub get
      working-directory: ./flutter_application_main
    - name: Run integration tests
      run: flutter test integration_test/app_test.dart
      working-directory: ./flutter_application_main

  build:
    needs: test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform: [ios, macos, chrome, android]
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
          channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
      working-directory: ./flutter_application_main
    - name: Build app for ${{ matrix.platform }}
      run: |
        if [ "${{ matrix.platform }}" == "ios" ]; then
          flutter build ios --release
        elif [ "${{ matrix.platform }}" == "macos" ]; then
          flutter build macos --release
        elif [ "${{ matrix.platform }}" == "chrome" ]; then
          flutter build web --release
        else
          flutter build apk --release
        fi
      working-directory: ./flutter_application_main

  release:
    needs: build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false
